crud_app/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  #this line gave us a new article path , patch path , delete path, show path, index path simply by
  resources :articles
end

crud_app/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

crud_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only:[:edit,:show,:destroy,:update]

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit 
       
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render'new'
        end 
    end

    def update
       
        if @article.update(article_params)
            flash[:notice]="Article was updated successfully"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show
       
    end

    def destroy       
        @article.destroy
        flash[:notice] = "Article was succesfully deleted"
        redirect_to articles_path
    end

    private

        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description)
        end

end

crud_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end

    def about

    end

end

crud_app/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @article do |f| %>
<p>
<%= f.label :title %><br/>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :description %><br/>
<%= f.text_area :description %>
</p>
<p>
<%= f.submit %>
</p>


<% end %>

<p><%= link_to 'Back to articles listing', articles_path %></p>

crud_app/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

crud_app/app/views/articles/index.html.erb
<h1>All articles listed here</h1>

<table>
<tr>
<th>Title</th>
<th>Description</th>
</tr>
<% @articles.each do |article| %>
<tr>
<td><%= article.title %></td>
<td><%= article.description %></td>
<td><%= button_to 'Edit', edit_article_path(article), method: :get %></td>
<td><%= button_to 'Show', article_path(article), method: :get %></td>
<td><%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
</tr>
<% end %>
</table>

<%# if we use button then we shall provide the method too and for link_to no need for method %>
<p><%= button_to "Create new article", new_article_path, method: :get %></p>

crud_app/app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

crud_app/app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>
<p><%= button_to 'Edit', edit_article_path(@article),method: :get %></p>

<p><%= button_to 'Delete', article_path(@article),method: :delete, data: {confirm:"Are you sure?"} %></p>

<p><%= button_to 'Back to articles listing', articles_path,method: :get %></p>

crud_app/app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <ul>
    <li>
        <%= msg %>
    </li>
    </ul>
<% end %>

crud_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>CrudApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>

  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

crud_app/app/views/pages/about.html.erb
<h1>This is basically a about page that even doesn't makes any sense</h1>
<%= link_to "Home",root_path %>

crud_app/app/views/pages/home.html.erb
<h1>This is basically a home page that makes no sense</h1>



<ul>
<li><%= link_to "About",about_path %></li>
<li><%= link_to "Articles", articles_path %></li>
</ul>